name: "Docker Copy Image"

on:
  workflow_dispatch:

jobs:
  copy_image:
    name: "Generate Docker image tag"
    runs-on: ubuntu-latest
    env:
      IMAGE_SRC: "nextcloud:32.0.6"
      IMAGE_DST: "ghcr.io/David-Lor/nextcloud:32.0.6"
    steps:
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Pull image"
        run: "docker pull ${{ env.IMAGE_SRC }}"
      - name: "Push Image"
        run: "docker push ${{ env.IMAGE_DST }}"
